### ISSUE TITLE
Cannot install com.tencent.meeting.deepin

### ISSUE THREAD

**Issue by Aloxaf** [actionless/pikaur#565] opened 2021-05-11 04:04 UTC
```
Pikaur v1.6.17
Pacman v5.2.2 - libalpm v12.0.2 - pyalpm v0.9.2
```

##### Description:

pikaur failed to resolve dependency `deepin-wine-helper>=5.1.19`, however there is `deepin-wine-helper-full` which provides `deepin-wine-helper=5.1.19`.

##### Attached log:

```
> pikaur -S com.tencent.meeting.deepin --verbose --pikaur-debug
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['com.tencent.meeting.deepin']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync com.tencent.meeting.deepin --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['com.tencent.meeting.deepin']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'com.tencent.meeting.deepin': <VersionMatcher com.tencent.meeting.deepin['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=com.tencent.meeting.deepin
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "com.tencent.meeting.deepin"   -> 2.8.7.400-2>]
Resolving AUR dependencies...
=> pacman --color=always --deptest deepin-wine6-stable>=6.0.0.3 deepin-wine-helper>=5.1.19 p7zip xdg-utils hicolor-icon-theme tar
=> pacman --color=always --sync --print-format=%% deepin-wine-helper>=5.1.19 deepin-wine6-stable>=6.0.0.3
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=deepin-wine-helper&arg[]=deepin-wine6-stable
:: error: Can't resolve dependencies for AUR package 'com.tencent.meeting.deepin':
Version mismatch:
com.tencent.meeting.deepin depends on: 'deepin-wine-helper>=5.1.19'
 found in 'PackageSource.AUR': '5.1.13-1'
```

**Comment by actionless** [comment] 2021-05-11 14:39
this is a duplicate of https://github.com/actionless/pikaur/issues/402

**Closed by actionless** 2021-05-11 14:39 UTC

**Comment by actionless** [comment] 2024-06-14 18:52
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
