### ISSUE TITLE
pikaur can not find an existing dependency

### ISSUE THREAD

**Issue by Anarky** [actionless/pikaur#620] opened 2022-01-08 10:05 UTC
```
pikaur -Vq
Pikaur v1.9
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:

On [pcsx2-git](https://aur.archlinux.org/packages/pcsx2-git/), the [rapidyaml-git](https://aur.archlinux.org/packages/rapidyaml-git/) dependency was newly added.
On system upgrade, `pikaur` complains that it can't find the `python-cmake-build-extension` dependency for `rapidyaml-git`, though [python-cmake-build-extension-git](https://aur.archlinux.org/packages/python-cmake-build-extension-git/) exists, which `provides` the non-git version.

##### Attached log:

```
$ pikaur -Syu
:: Synchronizing package databases...
[...]
Resolving AUR dependencies...
:: error: Can't resolve dependencies for AUR package 'rapidyaml-git':
:: error: Dependencies missing for rapidyaml-git, pcsx2-git
:: warning: Following package cannot be found in AUR:
    python-cmake-build-extension    
:: Try recovering rapidyaml-git?
[e] edit PKGBUILD
[s] skip this package
[A] abort
> 
```

Same issue if I try to install rapidyaml-git:
```
$ pikaur -S rapidyaml-git --verbose --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'rapidyaml-git', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['rapidyaml-git']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync rapidyaml-git --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['rapidyaml-git']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'rapidyaml-git': <VersionMatcher rapidyaml-git['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=rapidyaml-git
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "rapidyaml-git" 0.2.3.r21.gefc8b0e-1>]
    not_found_aur_pkgs=[]

:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "rapidyaml-git"   -> 0.2.3.r21.gefc8b0e-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest git cmake swig python-setuptools python-setuptools-scm python-cmake-build-extension python-pytest
=> pacman --color=always --sync --print-format=%% python-setuptools-scm python-cmake-build-extension python-pytest swig
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=python-cmake-build-extension
=> pacman --color=always --deptest python-cmake-build-extension
:: error: Can't resolve dependencies for AUR package 'rapidyaml-git':
:: error: Dependencies missing for rapidyaml-git
:: warning: Following package cannot be found in AUR:
    python-cmake-build-extension    
:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
:: Try recovering rapidyaml-git?
[e] edit PKGBUILD
[s] skip this package
[A] abort
> 
```

**Comment by actionless** [comment] 2022-01-11 11:12
that's ultimately duplicate of good ol https://github.com/actionless/pikaur/issues/402

considering the number of comments it received and times duplicates for it were created - it may be indeed time to give on waiting for proper implementation in AUR API and just parse the webpage: 

https://github.com/actionless/pikaur/issues/402#issuecomment-371321136
https://github.com/actionless/pikaur/issues/402#issuecomment-379898727
https://github.com/actionless/pikaur/issues/402#issuecomment-392991093

**Closed by actionless** 2022-01-11 11:12 UTC

**Comment by actionless** [comment] 2024-06-14 18:52
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
