### ISSUE TITLE
Can not install kata-runtime-bin package from aur

### ISSUE THREAD

**Issue by lisongmin** [actionless/pikaur#516] opened 2020-10-14 13:52 UTC
I can not install kata-runtime-bin package from aur. It seems pikaur do not get dependencies from providers field?
`yay` can resolve the dependencies at the same scenario.

```
❯ pikaur -Vq
Pikaur v1.6.12
Pacman v5.2.2 - libalpm v12.0.2
```

##### Attached log:

```
❯ pikaur -S kata-runtime-bin
[sudo] password for lsm: 
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: error: Can't resolve dependencies for AUR package 'kata-runtime-bin':
:: error: Dependencies missing for kata-runtime-bin
:: warning: Following packages cannot be found in AUR:
    kata-containers-image    
    kata-linux-container    
:: Try recovering?
[e] edit PKGBUILD
[s] skip this package
[A] abort
> a
```

```
❯ yay -S kata-runtime-bin
:: There are 3 providers available for kata-proxy:
:: Repository AUR
    1) kata-proxy 2) kata-proxy-bin 3) kata-proxy-git

Enter a number (default=1):
:: There are 3 providers available for kata-shim:
:: Repository AUR
    1) kata-shim 2) kata-shim-bin 3) kata-shim-git

Enter a number (default=1):
:: There are 3 providers available for kata-ksm-throttler:
:: Repository AUR
    1) kata-ksm-throttler 2) kata-ksm-throttler-bin 3) kata-ksm-throttler-git

Enter a number (default=1):
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:9]  seabios-1.14.0-1  numactl-2.0.14-1  libnfs-4.0.0-4  vde2-2.3.2-14  spice-0.14.3-2  libcacard-2.7.0-2  usbredir-0.8.0-2  liburing-0.7-2  qemu-headless-5.1.0-1
[Aur:6]  kata-containers-1.11.3-2 (kata-proxy kata-shim kata-ksm-throttler)  kata-containers-bin-1.11.3-1 (kata-containers-image-bin kata-linux-container-bin kata-runtime-bin)

:: Downloaded PKGBUILD (1/2): kata-containers (kata-proxy kata-shim kata-ksm-throttler)
:: Downloaded PKGBUILD (2/2): kata-containers-bin (kata-containers-image-bin kata-linux-container-bin kata-runtime-bin)
  2 kata-containers (kata-proxy kata-shim kata-ksm-throttler) (Build Files Exist)
  1 kata-containers-bin (kata-containers-image-bin kata-linux-container-bin kata-runtime-bin) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)

```

**Comment by actionless** [comment] 2020-10-14 13:57
duplicate of https://github.com/actionless/pikaur/issues/402

**Closed by actionless** 2020-10-14 13:57 UTC
Labels: duplicate

**Comment by actionless** [comment] 2024-06-14 18:52
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
