### ISSUE TITLE
Pikaur fails to find a package that provides the dependency under a different name

### ISSUE THREAD

**Issue by Anarky** [actionless/pikaur#676] opened 2022-11-20 19:45 UTC
```
$ pikaur -Vq
Pikaur v1.13.2
Pacman v6.0.2 - libalpm v13.0.2 - pyalpm v0.10.6
```

##### Description:
While trying to install [libretro-flycast-git](https://aur.archlinux.org/packages/libretro-flycast-git), pikaur can't find `libchdr` and `libchdr`, but they are provided by [libchdr-git](https://aur.archlinux.org/packages/libchdr-git).

Could it be because the [`depends` is inside the `package()` function](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=libretro-flycast-git#n66)?

##### Attached log:

```
$ pikaur -S libretro-flycast-git --verbose --pikaur-debug
:: debug: main: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'libretro-flycast-git', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['libretro-flycast-git']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
:: debug: install_info_fetcher: Checking if 'pkg_lines=['libretro-flycast-git']' is installable:
=> pacman --color=always --sync libretro-flycast-git --print-format %r/%n
:: debug: install_info_fetcher: Check failed - gonna check it separately:
:: debug: install_info_fetcher: Checking if 'libretro-flycast-git' exists in the repo:
=> pacman --color=always --sync libretro-flycast-git --print-format %r/%n --nodeps --nodeps
:: debug: install_info_fetcher:   'libretro-flycast-git' is NOT found in the repo.
:: debug: install_info_fetcher: Check partially passed - gonna get install infos:
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['libretro-flycast-git']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'libretro-flycast-git': <VersionMatcher libretro-flycast-git['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=libretro-flycast-git
:: debug: install_info_fetcher: found AUR pkgs:
    aur_pkg_list=[<AURPackageInfo "libretro-flycast-git" 2.0.r77.g993b705d-1>]
    not_found_aur_pkgs=[]

:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<AURInstallInfo "libretro-flycast-git"   -> 2.0.r77.g993b705d-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest glslang>=11.11 libretro-core-info libchdr.so libGL.so libminiupnpc.so libxxhash.so libzip.so cmake git glm libchdr libgl libzip miniupnpc vulkan-headers vulkan-icd-loader xbyak xxhash zlib
=> pacman --color=always --sync --print-format=%% --nodeps libchdr.so glm xbyak libchdr
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=libchdr.so&arg[]=xbyak&arg[]=libchdr
=> pacman --color=always --deptest libchdr.so
:: error: Can't resolve dependencies for AUR package 'libretro-flycast-git':
:: error: Dependencies missing for libretro-flycast-git
:: warning: Following packages cannot be found in AUR:
    libchdr.so    
    libchdr    
:: debug: prompt: Gonna get input from user...
:: debug: prompt_nolock: Restoring TTY...
:: debug: prompt_nolock: Using standard input reader...
:: Try recovering libretro-flycast-git?
[e] edit PKGBUILD
[s] skip this package
[A] abort
```

**Comment by actionless** [comment] 2022-11-23 14:11
duplicate of https://github.com/actionless/pikaur/issues/402

**Closed by actionless** 2022-11-23 14:11 UTC

**Comment by actionless** [comment] 2024-06-14 18:51
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
