### ISSUE TITLE
Running pikaur with sudo results in an AttributeError: FileLock object has no attribute lock_file

### ISSUE THREAD

**Issue by Dylan1496** [actionless/pikaur#610] opened 2021-12-08 20:49 UTC
```
$ pikaur -Vq
Pikaur v1.8
Pacman v6.0.1 - libalpm v13.0.1 - pyalpm v0.10.6
```

##### Description:
When running pikaur -S as root (using sudo), after being asked whether to edit the PKGBUILD or not, pikaur errors out with an AttributeError: 'FileLock' object has no attribute 'lock_file'.

##### Attached log:
Using sudo:
```
$ sudo pikaur -S pythia6 --verbose --pikaur-debug
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'pythia6', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['pythia6']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync pythia6 --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pythia6']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pythia6': <VersionMatcher pythia6['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pythia6
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "pythia6"   -> 4.28-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest gcc-fortran

:: AUR package will be installed:
 pythia6                                        -> 4.28-1

:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
:: debug: PROMPT: Reverting to prev TTY state...
:: debug: PROMPT: Got answer: 'y'
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/pythia6 pull origin master
looking for conflicting AUR packages...
:: warning: Not showing diff for pythia6 package (installing for the first time)
:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
Do you want to edit PKGBUILD for pythia6 package? [Y/n] n
:: debug: PROMPT: Reverting to prev TTY state...
:: debug: PROMPT: Got answer: 'n'

:: debug: Gonna build self.package_builds_by_name={'pythia6': <pikaur.build.PackageBuild object at 0x7f20e94e0af0>}
:: debug: Gonna build pkg_build.package_names=['pythia6']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/pythia6
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/pythia6/PKGBUILD /var/cache/private/pikaur/aur_repos/pythia6/.SRCINFO /var/cache/private/pikaur/build/pythia6/
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 36, in <module>
    main()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 352, in main
    cli_entry_point()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 268, in cli_entry_point
    pikaur_operation()
  File "/usr/lib/python3.9/site-packages/pikaur/main.py", line 117, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 161, in __init__
    self.main_sequence()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 180, in main_sequence
    self.install_packages()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 1018, in install_packages
    self.build_packages()
  File "/usr/lib/python3.9/site-packages/pikaur/install_cli.py", line 852, in build_packages
    pkg_build.build(
  File "/usr/lib/python3.9/site-packages/pikaur/build.py", line 755, in build
    self.install_all_deps(all_package_builds)
  File "/usr/lib/python3.9/site-packages/pikaur/build.py", line 553, in install_all_deps
    with FileLock(BUILD_DEPS_LOCK):
  File "/usr/lib/python3.9/site-packages/pikaur/filelock.py", line 16, in __init__
    self.lock_file = open(  # pylint: disable=consider-using-with
PermissionError: [Errno 13] Permission denied: '/tmp/pikaur_build_deps.lock'
Exception ignored in: <function FileLock.__del__ at 0x7f20e983d3a0>
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pikaur/filelock.py", line 42, in __del__
    self.__exit__()
  File "/usr/lib/python3.9/site-packages/pikaur/filelock.py", line 38, in __exit__
    if not self.lock_file.closed:
AttributeError: 'FileLock' object has no attribute 'lock_file'

```
Without sudo the makepkg function is called as usual (build fails, but this is not due to pikaur, but rather the source being down):
```
$ pikaur -S pythia6 --verbose --pikaur-debug
:: debug: Pikaur operation found for sys.argv=['/usr/bin/pikaur', '-S', 'pythia6', '--verbose', '--pikaur-debug']: cli_install_packages
:: debug: install_info_fetcher: Gonna fetch install info for:
    install_package_names=['pythia6']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

:: debug: install_info_fetcher: Gonna get repo pkgs install info...
Reading repository package databases...
Reading local package database...
=> pacman --color=always --sync pythia6 --print-format %r/%n
:: debug: install_info_fetcher: gonna get AUR pkgs install info for:
    aur_packages_versionmatchers=['pythia6']
    self.aur_updates_install_info=[]
    aur_packages_names_to_versions={'pythia6': <VersionMatcher pythia6['cmp_default']None>}
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=pythia6
:: debug: install_info_fetcher: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "pythia6"   -> 4.28-1>]
Resolving AUR dependencies...
=> pacman --color=always --deptest gcc-fortran

:: AUR package will be installed:
 pythia6                                        -> 4.28-1

:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
:: Proceed with installation? [Y/n] 
:: [v]iew package details   [m]anually select packages
>> y
:: debug: PROMPT: Reverting to prev TTY state...
:: debug: PROMPT: Got answer: 'y'
=> git clone https://aur.archlinux.org/pythia6.git /home/dylan/.local/share/pikaur/aur_repos/pythia6
looking for conflicting AUR packages...
:: warning: Not showing diff for pythia6 package (installing for the first time)
:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
Do you want to edit PKGBUILD for pythia6 package? [Y/n] n
:: debug: PROMPT: Reverting to prev TTY state...
:: debug: PROMPT: Got answer: 'n'

:: debug: Gonna build self.package_builds_by_name={'pythia6': <pikaur.build.PackageBuild object at 0x7f0a85fe5580>}
:: debug: Gonna build pkg_build.package_names=['pythia6']
=> mkdir -p /home/dylan/.cache/pikaur/build/pythia6
=> cp -r /home/dylan/.local/share/pikaur/aur_repos/pythia6/PKGBUILD /home/dylan/.local/share/pikaur/aur_repos/pythia6/.SRCINFO /home/dylan/.cache/pikaur/build/pythia6/
=> makepkg --packagelist

:: Starting the build:
=> makepkg --force
==> Making package: pythia6 4.28-1 (Wed 08 Dec 2021 03:42:33 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading pythia6.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  554k  100  554k    0     0   493k      0  0:00:01  0:00:01 --:--:--  493k
  -> Downloading pythia-6.4.28.f.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243  100   243    0     0    610      0 --:--:-- --:--:-- --:--:--   610
100   269  100   269    0     0    257      0  0:00:01  0:00:01 --:--:--  2690
100   112  100   112    0     0     89      0  0:00:01  0:00:01 --:--:--    89
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
==> ERROR: Failure while downloading http://www.hepforge.org/archive/pythia6/pythia-6.4.28.f.gz
    Aborting...

Command 'makepkg --force' failed to execute.
:: debug: PROMPT: Gonna get input from user...
:: debug: PROMPT: Restoring TTY...
:: debug: PROMPT: Using standard input reader...
:: Try recovering?
[R] retry build
[p] PGP check skip
[c] checksums skip
[i] ignore architecture
[d] delete build dir and try again
[e] edit PKGBUILD
------------------------
[s] skip building this package
[a] abort building all the packages
> s
:: debug: PROMPT: Reverting to prev TTY state...
:: debug: PROMPT: Got answer: 's'

Can't build 'pythia6'.

:: debug: install_cli: discarding install info for pkg... pythia6
:: debug: install_cli: ignoring pkg... pythia6
:: debug: install_info_fetcher: discarding canceled_pkg_name='pythia6'
:: debug: install_cli: discarded install info for pkg: pythia6
Failed to build following packages:
pythia6
```

**Comment by actionless** [comment] 2021-12-14 18:53
> PermissionError: [Errno 13] Permission denied: '/tmp/pikaur_build_deps.lock'

as i see from the log this is the root cause - for some reason this stopped working from under SystemD Dynamic Users - mb path should be changed to some tempdir inside there

**Comment by tilsche** [comment] 2021-12-26 20:10
Is there a workaround or short-term-fix for this?

**Closed** 2021-12-26 20:50 UTC
Labels: bug, root / sudo / systemd dynamic users

**Comment by codebling** [comment] 2021-12-28 21:41
@tilsche `rm /tmp/pikaur_build_deps.lock`

**Comment by actionless** [comment] 2021-12-28 22:46
@codebling dont think it will help without upgrading `pikaur-git` first

**Comment by codebling** [comment] 2021-12-28 22:53
`pikaur -S --rebuild pikaur && rm /tmp/pikaur_build_deps.lock` worked for me without upgrading

**Comment by actionless** [comment] 2021-12-28 23:23
i guess it would break again as soon as someone would run pikaur again from a non-root user, but anyway i'll do release soon including that fix so this topic is not relevant :D
