### ISSUE TITLE
pikaur constantly use 100% CPU on WSL

### ISSUE THREAD

**Issue by wangqr** [actionless/pikaur#317] opened 2018-11-30 01:43 UTC
```
pikaur -Vq
Pikaur v1.3.1
Pacman v5.1.1 - libalpm v11.0.1
```
Archlinux is running on Windows Subsystem Linux, on windows 10 1809.
##### Attached log:

```
pikaur -S caffe
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...

:: AUR package will be installed:
 caffe                                                      -> 1.0-14

:: Proceed with installation? [Y/n]
:: [v]iew package details   [m]anually select packages
>>
```
Just leave it there without answering anything. Open htop and I can see that pikaur is using 100% CPU (full of a single core). `caffe` can be changed to any package.

I ran pikaur with PyCharm profiler, and get the following image:
![pikaur5](https://user-images.githubusercontent.com/8182182/49263141-43940780-f417-11e8-809d-eac3c5370109.png)

**Comment by wangqr** [comment] 2018-11-30 01:50
And the original pstat file from the profiler:
[pikaur5.zip](https://github.com/actionless/pikaur/files/2631644/pikaur5.zip)

**Comment by actionless** [comment] 2018-11-30 02:56
please run pikaur with `--debug` flag and hit `Ctrl+C` while it happens to see the stack trace

**Comment by actionless** [comment] 2018-11-30 03:02
but profiling results are confusing for me, 

```pstat
  ncalls  tottime  percall  cumtime  percall filename:lineno(function)
       28   66.495    2.375   66.495    2.375 {method 'acquire' of '_thread.lock' objects}
```

it saying what each acquiring of the lock was taking more than 2 seconds


can you reproduce it in any other environment? i don't have windows for reproducing it

**Comment by actionless** [comment] 2018-11-30 03:12
also please check if setting `sudoloopinterval = 60` (or bigger) in `/.confg/pikaur.conf` makes any difference

**Comment by wangqr** [comment] 2018-11-30 13:20
> 
> 
> please run pikaur with `--debug` flag and hit `Ctrl+C` while it happens to see the stack trace

```
Traceback (most recent call last):
  File "/usr/sbin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 328, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 238, in cli_entry                                                                                        _point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_                                                                                        sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 677, in get
    self.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 674, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```

> 
> 
> also please check if setting `sudoloopinterval = 60` (or bigger) in `/.confg/pikaur.conf` makes any difference
Yes, this solves the issue.

**Comment by actionless** [comment] 2018-11-30 14:02
so, either threadlock implmentation or `sudo -v` is buggy under windows (unless you can't reproduce it somewhere else)

**Comment by wangqr** [comment] 2018-11-30 18:58
If I take the 2 functions out (see [this gist](https://gist.github.com/wangqr/76752502264b371befa763fb173608ba)), the CPU usage is normal (nearly 0)

**Comment by actionless** [comment] 2018-11-30 19:08
Is there any difference if you replace sleep to something what will be
actually executing in that thread, for example print smth each second?

**Comment by wangqr** [comment] 2018-12-01 05:04
I tried various functions. I found that this issue can be reproduced with [this example](https://gist.github.com/wangqr/95558e88db5e1392bda8af0c94276133) on my computer.

**Comment by actionless** [comment] 2018-12-01 22:13
if debugging with `gdb` also fails in a same way as `strace`?

**Comment by actionless** [comment] 2018-12-13 21:49
if you don't mind i am closing this since the issue is also reproducible with gzip

**Closed by actionless** 2018-12-13 21:49 UTC
Labels: upstream issue
