### ISSUE TITLE
Not able to resolve alternative dependency

### ISSUE THREAD

**Issue by husjon** [actionless/pikaur#400] opened 2019-09-28 18:25 UTC
```
pikaur -Vq
Pikaur v1.5.2
Pacman v5.1.3 - libalpm v11.0.3
```

##### Attached log:

```
pikaur -S xtensa-esp32-elf-gcc-bin
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: error: Can't resolve dependencies for AUR package 'xtensa-esp32-elf-gcc-bin':
:: error: Dependencies missing for xtensa-esp32-elf-gcc-bin
:: warning: Following package cannot be found in AUR:
    python2-pyelftools
```

https://aur.archlinux.org/packages/xtensa-esp32-elf-gcc-bin/
AUR lists the following dependency:
```python2-pyelftools (python2-pyelftools-git)```

Tested with yay and this seems to work, which I in the end used to install the dependency first, then use pikaur to install `xtensa-esp32-elf-gcc-bin`

**Comment by mattia-b89** [comment] 2019-10-01 13:18
I confirm the issue, but we have to  clarify  
that `python2-pyelftools` is _provided_ by `python2-pyelftools-git` package, which in it turns is part of `python-pyelftools-git` package base

**Comment by actionless** [comment] 2019-10-02 00:10
duplicate of https://github.com/actionless/pikaur/issues/402

**Closed by actionless** 2019-10-02 00:10 UTC

**Comment by actionless** [comment] 2024-06-14 18:52
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.

**Comment by husjon** [comment] 2024-06-14 20:29
Unfortunately I'm no longer using Archlinux but thanks for looking into it.
