### ISSUE TITLE
pikaur break while trying to build a package   -version 1.3.2

### ISSUE THREAD

**Issue by bionade24** [actionless/pikaur#323] opened 2018-12-12 19:25 UTC
Happens since 1.3.2, 1.3.1 was okay
Running `pikaur -S pkg_already_installed --rebuild` it first works, until you should get the message if you want to see the pkg build, normally it should mark the N as default (`[j/N]`) since you already saw this pkgbuild, but instead you get this error;
```
  File "/usr/bin/pikaur", line 9, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 328, in main
    cli_entry_point()
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 238, in cli_entry_point
    run_with_sudo_loop(pikaur_operation)
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 257, in run_with_sudo_loop
    raise catched_exc  # pylint: disable=raising-bad-type
  File "/usr/lib/python3.7/site-packages/pikaur/core.py", line 251, in run_with_sudo_loop
    result = main_thread.get()
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
  File "/usr/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.7/site-packages/pikaur/main.py", line 100, in cli_install_packages
    InstallPackagesCLI()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 150, in __init__
    self.review_build_files()
  File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 566, in review_build_files
    reason=_("already reviewed")
KeyError: 'package'
```
I also got this with other installed packages wich were a dependency of a new package.

**Comment by bionade24** [comment] 2018-12-12 19:33
One other posted the same issue at the AUR page:
```
vivaeltopo commented on 2018-12-10 09:06
1.3.2-1 fails when updating aur packages:

File "/usr/lib/python3.7/site-packages/pikaur/install_cli.py", line 561, in review_build_files reason=_("installing for the first time") KeyError: 'package'

1.3.1 was fine
```

**Comment by actionless** [comment] 2018-12-12 19:37
duplicate of https://github.com/actionless/pikaur/issues/319

i'll better make a release now until more people starting to have that problem

**Closed by actionless** 2018-12-12 19:37 UTC

**Comment by actionless** [comment] 2018-12-12 19:43
released

**Comment by bionade24** [comment] 2018-12-12 20:00
Thanks! I searched but haven't found the duplicate. And thanks for pikaur, too.
