### ISSUE TITLE
Unable to install or upgrade packages

### ISSUE THREAD

**Issue by M4tT3d** [actionless/pikaur#473] opened 2020-04-12 18:21 UTC
Hi. As I wrote in the title, with the last update I can no longer install or update packages using pikaur. the terminal stuck in "I'm starting the creation of the package". What can I do? I've tried other wrappers and they work, so I don't know what the problem may be. thank you all in advance
```
pikaur -Vq
Pikaur v1.6.9.1
Pacman v5.2.1 - libalpm v12.0.1
```

##### Attached log:

**Install test**
```
sudo pikaur -S mailspring --verbose --pikaur-debug                                                  

=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
:: debug: Gonna fetch install info for:
    install_package_names=['mailspring']
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

Sto leggendo i database dei pacchetti nel repository...
Sto leggendo il database locale dei pacchetti...
=> pacman --color=always --sync mailspring --print-format %r/%n
:: debug: gonna get AUR pkgs install info... self.aur_updates_install_info=[]
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=mailspring
:: debug: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "mailspring"   -> 1.7.4-1>]
Risoluzione delle dipendenze AUR...
=> pacman --color=always --deptest libxss libtool c-ares ctemplate tidy libxkbfile libsecret gconf gtk3 nss libglvnd
=> pacman --color=always --sync --print-format=%% gconf c-ares tidy ctemplate
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=gconf
=> pacman --color=always --deptest libxml2 polkit libldap dbus-glib python intltool gtk-doc gobject-introspection git gnome-common
=> pacman --color=always --sync --print-format=%% gobject-introspection intltool gtk-doc gnome-common
=> pacman --color=always --deptest libxss libtool c-ares ctemplate tidy libxkbfile libsecret gconf gtk3 nss libglvnd
=> pacman --color=always --deptest libxml2 polkit libldap dbus-glib python intltool gtk-doc gobject-introspection git gnome-common
=> pacman --color=always --sync c-ares --print-format %r/%n
=> pacman --color=always --sync intltool --print-format %r/%n
=> pacman --color=always --sync ctemplate --print-format %r/%n
=> pacman --color=always --sync gtk-doc --print-format %r/%n
=> pacman --color=always --sync tidy --print-format %r/%n
=> pacman --color=always --sync gobject-introspection --print-format %r/%n
=> pacman --color=always --sync gnome-common --print-format %r/%n
=> pacman --color=always --sync --needed tidy gtk-doc intltool gobject-introspection c-ares ctemplate gnome-common --print-format %r/%n

:: Le nuove dipendenze verranno installate dal repository:
 autoconf-archive (per gnome-common)                        -> 1:2019.01.06-1
 c-ares (per mailspring)                                    -> 1.16.0-1
 ctemplate (per mailspring)                                 -> 2.4-1
 docbook-xml (per docbook-xsl, gtk-doc, itstool)            -> 4.5-8
 docbook-xsl (per gtk-doc, yelp-tools)                      -> 1.79.2-5
 glib2-docs (per gtk-doc)                                   -> 2.64.2-1
 gnome-common (per gconf)                                   -> 3.18.0-3
 gobject-introspection (per gconf)                          -> 1.64.1-2
 gobject-introspection-runtime (per gobject-introspection)    -> 1.64.1-2
 gtk-doc (per gnome-common, gconf)                          -> 1.32+37+gefc3644-1
 intltool (per gnome-common, gconf)                         -> 0.51.0-4
 itstool (per yelp-tools)                                   -> 1:2.0.6-1
 mallard-ducktype (per yelp-tools)                          -> 1.0.2-3
 perl-encode-locale (per perl-http-message, perl-libwww)    -> 1.05-5
 perl-file-listing (per perl-libwww)                        -> 6.04-6
 perl-html-parser (per perl-libwww)                         -> 3.72-8
 perl-html-tagset (per perl-html-parser)                    -> 3.20-8
 perl-http-cookies (per perl-libwww)                        -> 6.08-1
 perl-http-daemon (per perl-libwww)                         -> 6.06-1
 perl-http-date (per perl-file-listing, perl-http-message, perl-http-cookies, perl-http-daemon, perl-libwww)    -> 6.05-1
 perl-http-message (per perl-http-cookies, perl-http-daemon, perl-http-negotiate)    -> 6.22-1
 perl-http-negotiate (per perl-libwww)                      -> 6.01-6
 perl-io-html (per perl-http-message)                       -> 1.001-5
 perl-libwww (per perl-xml-parser)                          -> 6.43-1
 perl-lwp-mediatypes (per perl-http-message, perl-http-daemon, perl-libwww)    -> 6.02-6
 perl-net-http (per perl-libwww)                            -> 6.19-2
 perl-try-tiny (per perl-libwww)                            -> 0.30-3
 perl-uri (per perl-http-message, perl-www-robotrules, perl-libwww)    -> 1.76-2
 perl-www-robotrules (per perl-libwww)                      -> 6.02-6
 perl-xml-parser (per intltool)                             -> 2.46-1
 python-anytree (per gtk-doc)                          

##### [Optional] Prerequisites:


     -> 2.8.0-1
 python-appdirs (per python-setuptools)                     -> 1.4.3-5
 python-beaker (per python-mako)                            -> 1.11.0-3
 python-lxml (per gtk-doc)                                  -> 4.5.0-1
 python-mako (per gobject-introspection)                    -> 1.1.2-1
 python-markdown (per gobject-introspection)                -> 3.1.1-4
 python-markupsafe (per python-mako)                        -> 1.1.1-3
 python-ordered-set (per python-setuptools)                 -> 3.1.1-1
 python-packaging (per python-setuptools)                   -> 20.3-1
 python-pygments (per gtk-doc)                              -> 2.6.1-2
 python-pyparsing (per python-packaging)                    -> 2.4.7-1
 python-setuptools (per python-pygments, python-mako, python-markdown)    -> 1:46.1.3-1
 python-six (per python-packaging, python-anytree)          -> 1.14.0-1
 tidy (per mailspring)                                      -> 5.7.16-1
 yelp-tools (per gnome-common)                              -> 3.32.2-1
 yelp-xsl (per yelp-tools)                                  -> 3.36.0-1

:: Il pacchetto AUR verrà installato:
 mailspring                                                 -> 1.7.4-1 [vecchio: 2020/04/05]

:: La nuova dipendenza verrà installata da AUR:
 gconf (per mailspring)                                     -> 3.2.6+11+g07808097-6

:: Procedere con l'installazione? [S/n]
:: [v]edi i dettagli del pacchetto   seleziona [m]anualmente i pacchetti
>> s
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/mailspring pull origin master
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/gconf pull origin master
=> pacman --color=always --deptest libxss libtool c-ares ctemplate tidy libxkbfile libsecret gconf gtk3 nss libglvnd
=> pacman --color=always --deptest libxml2 polkit libldap dbus-glib python
=> pacman --color=always --deptest intltool gtk-doc gobject-introspection git gnome-common
in cerca di pacchetti AUR in conflitto...
=> pacman --color=always --deptest libxss libtool c-ares ctemplate tidy libxkbfile libsecret gconf gtk3 nss libglvnd
=> pacman --color=always --deptest libxml2 polkit libldap dbus-glib python intltool gtk-doc gobject-introspection git gnome-common
:: attenzione: Impossibile mostra il diff per il pacchetto mailspring (sto installando per la prima volta)
Vuoi modifica PKGBUILD per il pacchetto mailspring? [S/n] n
:: attenzione: Impossibile mostra il diff per il pacchetto gconf (sto installando per la prima volta)
Vuoi modifica PKGBUILD per il pacchetto gconf? [S/n] n
Vuoi modifica gconf.install per il pacchetto gconf? [S/n] n

:: debug: Gonna build self.package_builds_by_name={'mailspring': <pikaur.build.PackageBuild object at 0x7fa0770d6910>, 'gconf': <pikaur.build.PackageBuild object at 0x7fa0770ed1f0>}
:: debug: Gonna build pkg_build.package_names=['gconf']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/gconf
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/gconf/PKGBUILD /var/cache/private/pikaur/aur_repos/gconf/gconfpkg /var/cache/private/pikaur/aur_repos/gconf/gconf-install.hook /var/cache/private/pikaur/aur_repos/gconf/gconf-reload.patch /var/cache/private/pikaur/aur_repos/gconf/01_xml-gettext-domain.patch /var/cache/private/pikaur/aur_repos/gconf/gconf-merge-schema /var/cache/private/pikaur/aur_repos/gconf/gconf-remove.hook /var/cache/private/pikaur/aur_repos/gconf/gconf.install /var/cache/private/pikaur/aur_repos/gconf/.SRCINFO /var/cache/private/pikaur/build/gconf/
=> pacman --color=always --deptest intltool gtk-doc gobject-introspection git gnome-common
Sto leggendo il database locale dei pacchetti...
=> pacman --color=always --deptest libxml2 polkit libldap dbus-glib python
=> pacman --color=always --deptest intltool gtk-doc gobject-introspection git gnome-common
:: Installazione delle dipendenze da repository per gconf:
=> pacman --color=always --sync --asdeps gobject-introspection intltool gtk-doc gnome-common
risoluzione delle dipendenze in corso...
ricerca dei pacchetti in conflitto in corso...

Pacchetti (43) autoconf-archive-1:2019.01.06-1  docbook-xml-4.5-8  docbook-xsl-1.79.2-5  glib2-docs-2.64.2-1
               gobject-introspection-runtime-1.64.1-2  itstool-1:2.0.6-1  mallard-ducktype-1.0.2-3
               perl-encode-locale-1.05-5  perl-file-listing-6.04-6  perl-html-parser-3.72-8  perl-html-tagset-3.20-8
               perl-http-cookies-6.08-1  perl-http-daemon-6.06-1  perl-http-date-6.05-1  perl-http-message-6.22-1
               perl-http-negotiate-6.01-6  perl-io-html-1.001-5  perl-libwww-6.43-1  perl-lwp-mediatypes-6.02-6
               perl-net-http-6.19-2  perl-try-tiny-0.30-3  perl-uri-1.76-2  perl-www-robotrules-6.02-6
               perl-xml-parser-2.46-1  python-anytree-2.8.0-1  python-appdirs-1.4.3-5  python-beaker-1.11.0-3
               python-lxml-4.5.0-1  python-mako-1.1.2-1  python-markdown-3.1.1-4  python-markupsafe-1.1.1-3
               python-ordered-set-3.1.1-1  python-packaging-20.3-1  python-pygments-2.6.1-2  python-pyparsing-2.4.7-1
               python-setuptools-1:46.1.3-1  python-six-1.14.0-1  yelp-tools-3.32.2-1  yelp-xsl-3.36.0-1
               gnome-common-3.18.0-3  gobject-introspection-1.64.1-2  gtk-doc-1.32+37+gefc3644-1  intltool-0.51.0-4

Dimensione totale dei pacchetti da scaricare:    2,66 MiB
Dimensione totale dei pacchetti da installare:  89,59 MiB

:: Vuoi procedere con l'installazione? [S/n] S
:: Download dei pacchetti in corso...
 glib2-docs-2.64.2-1-x86_64                    1342,6 KiB  6,90 MiB/s 00:00 [##########################################] 100%
 gobject-introspection-runtime-1.64.1-2-x86_64  216,6 KiB  21,1 MiB/s 00:00 [##########################################] 100%
 gobject-introspection-1.64.1-2-x86_64         1168,0 KiB  7,45 MiB/s 00:00 [##########################################] 100%
(43/43) verifica delle chiavi presenti nel portachiavi                      [##########################################] 100%
(43/43) verifica dell'integrità dei pacchetti                               [##########################################] 100%
(43/43) caricamento dei file dei pacchetti                                  [##########################################] 100%
(43/43) controllo dei conflitti in corso                                    [##########################################] 100%
(43/43) controllo dello spazio disponibile sul disco                        [##########################################] 100%
:: Elaborazione delle modifiche al pacchetto...
( 1/43) installazione in corso di python-markupsafe                         [##########################################] 100%
( 2/43) installazione in corso di python-beaker                             [##########################################] 100%
( 3/43) installazione in corso di python-appdirs                            [##########################################] 100%
( 4/43) installazione in corso di python-pyparsing                          [##########################################] 100%
( 5/43) installazione in corso di python-six                                [##########################################] 100%
( 6/43) installazione in corso di python-packaging                          [##########################################] 100%
( 7/43) installazione in corso di python-ordered-set                        [##########################################] 100%
( 8/43) installazione in corso di python-setuptools                         [##########################################] 100%
( 9/43) installazione in corso di python-mako                               [##########################################] 100%
(10/43) installazione in corso di python-markdown                           [##########################################] 100%
(11/43) installazione in corso di gobject-introspection-runtime             [##########################################] 100%
(12/43) installazione in corso di gobject-introspection                     [##########################################] 100%
(13/43) installazione in corso di perl-encode-locale                        [##########################################] 100%
(14/43) installazione in corso di perl-http-date                            [##########################################] 100%
(15/43) installazione in corso di perl-file-listing                         [##########################################] 100%
(16/43) installazione in corso di perl-html-tagset                          [##########################################] 100%
(17/43) installazione in corso di perl-html-parser                          [##########################################] 100%
(18/43) installazione in corso di perl-lwp-mediatypes                       [##########################################] 100%
(19/43) installazione in corso di perl-uri                                  [##########################################] 100%
(20/43) installazione in corso di perl-io-html                              [##########################################] 100%
(21/43) installazione in corso di perl-http-message                         [##########################################] 100%
(22/43) installazione in corso di perl-http-cookies                         [##########################################] 100%
(23/43) installazione in corso di perl-http-daemon                          [##########################################] 100%
(24/43) installazione in corso di perl-http-negotiate                       [##########################################] 100%
(25/43) installazione in corso di perl-net-http                             [##########################################] 100%
(26/43) installazione in corso di perl-try-tiny                             [##########################################] 100%
(27/43) installazione in corso di perl-www-robotrules                       [##########################################] 100%
(28/43) installazione in corso di perl-libwww                               [##########################################] 100%
Dipendenze opzionali di perl-libwww
    perl-lwp-protocol-https: for https:// url schemes
(29/43) installazione in corso di perl-xml-parser                           [##########################################] 100%
(30/43) installazione in corso di intltool                                  [##########################################] 100%
(31/43) installazione in corso di docbook-xml                               [##########################################] 100%
(32/43) installazione in corso di docbook-xsl                               [##########################################] 100%
(33/43) installazione in corso di glib2-docs                                [##########################################] 100%
(34/43) installazione in corso di python-lxml                               [##########################################] 100%
Dipendenze opzionali di python-lxml
    python-beautifulsoup4: support for beautifulsoup parser to parse not well formed HTML
    python-cssselect: support for cssselect
    python-html5lib: support for html5lib parser
    python-lxml-docs: offline docs
(35/43) installazione in corso di python-pygments                           [##########################################] 100%
(36/43) installazione in corso di python-anytree                            [##########################################] 100%
(37/43) installazione in corso di gtk-doc                                   [##########################################] 100%
Dipendenze opzionali di gtk-doc
    dblatex: PDF support
(38/43) installazione in corso di autoconf-archive                          [##########################################] 100%
Dipendenze opzionali di autoconf-archive
    automake: macros for use with it [installato]
(39/43) installazione in corso di yelp-xsl                                  [##########################################] 100%
(40/43) installazione in corso di itstool                                   [##########################################] 100%
(41/43) installazione in corso di mallard-ducktype                          [##########################################] 100%
(42/43) installazione in corso di yelp-tools                                [##########################################] 100%
(43/43) installazione in corso di gnome-common                              [##########################################] 100%
:: Esecuzione degli hook di post-transazione...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Cleaning pacman cache...
==> no candidate packages found for pruning
(3/4) Warn about old perl modules
(4/4) Updating the info directory file...
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/gconf makepkg --packagelist

:: Sto iniziando la creazione del pacchetto:
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/gconf makepkg --force
```
**STUCK AT THIS**

**Upgrade test**
```
sudo pikaur -Syu --verbose --pikaur-debug
                                                                        
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp true
=> GET https://www.archlinux.org/feeds/news/
=> pacman --color=always --sync --refresh
:: Sincronizzazione dei database in corso...
 core è aggiornato
 extra è aggiornato
 community è aggiornato
 repo-ck è aggiornato

:: Inizio un aggiornamento completo di AUR...
:: debug: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=[]

Sto leggendo i database dei pacchetti nel repository...
Sto leggendo il database locale dei pacchetti...
=> pacman --color=always --sync --sysupgrade --print-format %r/%n
:: debug: gonna get AUR pkgs install info... self.aur_updates_install_info=[]
Sto leggendo le informazioni dei pacchetti AUR...
=> GET https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=android-emulator&arg[]=android-sdk&arg[]=android-sdk-platform-tools&arg[]=barrier&arg[]=barrier-headless&arg[]=downgrade&arg[]=gconf&arg[]=gitkraken&arg[]=google-chrome&arg[]=libinput-gestures&arg[]=llvm-libs-git&arg[]=mailspring&arg[]=ncurses5-compat-libs&arg[]=otf-san-francisco-mono&arg[]=otf-san-francisco-pro&arg[]=pikaur&arg[]=plasma5-applets-eventcalendar&arg[]=slack-desktop&arg[]=snapd&arg[]=spotify&arg[]=visual-studio-code-bin
:: debug: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "llvm-libs-git" 10.0.0_r329190.644abcf09d6-1 -> 11.0.0_r346859.84aa6cf1a9f-1>, <InstallInfo "mailspring" 1.7.2-1 -> 1.7.4-1>, <InstallInfo "snapd" 2.44.1-1 -> 2.44.2-1>]
Risoluzione delle dipendenze AUR...
=> pacman --color=always --deptest squashfs-tools libseccomp libsystemd apparmor git go go-tools libcap systemd xfsprogs python-docutils
=> pacman --color=always --deptest libxss libtool c-ares ctemplate tidy libxkbfile libsecret gconf gtk3 nss libglvnd
=> pacman --color=always --deptest gcc-libs zlib libffi libedit ncurses libxml2 git cmake ninja python-sphinx ocaml ocaml-ctypes ocaml-findlib python-recommonmark swig python python-six python-psutil
=> pacman --color=always --sync --print-format=%% ocaml cmake python-recommonmark python-sphinx swig ninja ocaml-ctypes python-psutil ocaml-findlib
=> pacman --color=always --deptest gcc-libs zlib libffi libedit ncurses libxml2 git cmake ninja python-sphinx ocaml ocaml-ctypes ocaml-findlib python-recommonmark swig python python-six python-psutil
=> pacman --color=always --sync cmake --print-format %r/%n
=> pacman --color=always --sync ninja --print-format %r/%n
=> pacman --color=always --sync python-sphinx --print-format %r/%n
=> pacman --color=always --sync ocaml --print-format %r/%n
=> pacman --color=always --sync ocaml-ctypes --print-format %r/%n
=> pacman --color=always --sync ocaml-findlib --print-format %r/%n
=> pacman --color=always --sync python-recommonmark --print-format %r/%n
=> pacman --color=always --sync swig --print-format %r/%n
=> pacman --color=always --sync python-psutil --print-format %r/%n
=> pacman --color=always --sync --needed python-sphinx python-psutil ocaml python-recommonmark cmake swig ocaml-ctypes ocaml-findlib ninja --print-format %r/%n

:: Il pacchetto da repository sarà installato:
 dolphin                               19.12.3-1            -> 19.12.3-2

:: Le nuove dipendenze verranno installate dal repository:
 cmake (per llvm-libs-git)                                  -> 3.17.1-1
 jsoncpp (per cmake, cmake)                                 -> 1.9.2-1
 libuv (per cmake)                                          -> 1.35.0-1
 ninja (per llvm-libs-git)                                  -> 1.10.0-1
 ocaml (per ocaml-ctypes, ocaml-compiler-libs, llvm-libs-git)    -> 4.09.1-1
 ocaml-compiler-libs (per ocaml-findlib)                    -> 4.09.1-1
 ocaml-ctypes (per llvm-libs-git)                           -> 0.17.1-2
 ocaml-findlib (per llvm-libs-git)                          -> 1.8.1-5
 ocaml-integers (per ocaml-ctypes)                          -> 0.3.0-4
 python-babel (per python-sphinx)                           -> 2.8.0-4
 python-commonmark (per python-recommonmark)                -> 0.9.1-1
 python-future (per python-commonmark)                      -> 0.18.2-2
 python-imagesize (per python-sphinx)                       -> 1.2.0-1
 python-jinja (per python-sphinx)                           -> 2.11.1-1
 python-markupsafe (per python-jinja)                       -> 1.1.1-3
 python-psutil (per llvm-libs-git)                          -> 5.7.0-1
 python-pygments (per python-sphinx)                        -> 2.6.1-2
 python-pytz (per python-babel)                             -> 2019.3-3
 python-recommonmark (per llvm-libs-git)                    -> 0.6.0.194.48f9d1a-2
 python-snowballstemmer (per python-sphinx)                 -> 2.0.0-3
 python-sphinx (per python-recommonmark, llvm-libs-git)     -> 3.0.1-1
 python-sphinx-alabaster-theme (per python-sphinx)          -> 0.7.12-3
 python-sphinxcontrib-applehelp (per python-sphinx)         -> 1.0.2-1
 python-sphinxcontrib-devhelp (per python-sphinx)           -> 1.0.2-1
 python-sphinxcontrib-htmlhelp (per python-sphinx)          -> 1.0.3-1
 python-sphinxcontrib-jsmath (per python-sphinx)            -> 1.0.1-4
 python-sphinxcontrib-qthelp (per python-sphinx)            -> 1.0.3-1
 python-sphinxcontrib-serializinghtml (per python-sphinx)    -> 1.1.4-1
 rhash (per cmake)                                          -> 1.3.9-1
 swig (per llvm-libs-git)                                   -> 4.0.1-2

:: I pacchetti AUR verranno installati:
 llvm-libs-git                         10.0.0_r329190.644abcf09d6-1  -> 11.0.0_r346859.84aa6cf1a9f-1
 mailspring                            1.7.2-1              -> 1.7.4-1 [vecchio: 2020/04/05]
 snapd                                 2.44.1-1             -> 2.44.2-1 [vecchio: 2020/04/10]

:: Procedere con l'installazione? [S/n]
:: [v]edi i dettagli del pacchetto   seleziona [m]anualmente i pacchetti
>> m

=> /usr/bin/nano /tmp/tmp89grlv3n
:: debug: Gonna fetch install info for:
    install_package_names=[]
    not_found_repo_pkgs_names=[]
    pkgbuilds_packagelists={}
    manually_excluded_packages_names=['mailspring', 'dolphin', 'llvm-libs-git']

:: Ignoro l'aggiornamento del pacchetto dolphin (19.12.3-1 => 19.12.3-2)
:: debug: gonna get AUR pkgs install info... self.aur_updates_install_info=[]
Sto leggendo le informazioni dei pacchetti AUR...
:: Ignoro l'aggiornamento del pacchetto llvm-libs-git (10.0.0_r329190.644abcf09d6-1 => 11.0.0_r346859.84aa6cf1a9f-1)
:: Ignoro l'aggiornamento del pacchetto mailspring (1.7.2-1 => 1.7.4-1)
:: debug: got AUR pkgs install info: self.aur_updates_install_info=[<InstallInfo "snapd" 2.44.1-1 -> 2.44.2-1>]
Risoluzione delle dipendenze AUR...

:: Il pacchetto AUR verrà installato:
 snapd                                 2.44.1-1             -> 2.44.2-1 [vecchio: 2020/04/10]

:: Procedere con l'installazione? [S/n]
:: [v]edi i dettagli del pacchetto   seleziona [m]anualmente i pacchetti
>> s
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp git -C /var/cache/pikaur/aur_repos/snapd pull origin master
=> pacman --color=always --deptest squashfs-tools libseccomp libsystemd apparmor
=> pacman --color=always --deptest git go go-tools libseccomp libcap systemd xfsprogs python-docutils apparmor
in cerca di pacchetti AUR in conflitto...
Vuoi vedere il diff per il pacchetto snapd? [S/n] n
Vuoi modifica PKGBUILD per il pacchetto snapd? [s/N] n
Vuoi modifica snapd.install per il pacchetto snapd? [s/N] n

=> pacman --color=always --sync --verbose --sysupgrade --ignore mailspring --ignore dolphin --ignore llvm-libs-git
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : Nessuno
:: Aggiornamento del sistema in corso...
attenzione: dolphin: l'aggiornamento del pacchetto è stato ignorato (19.12.3-1 => 19.12.3-2)
 non ci sono aggiornamenti disponibili
:: debug: Gonna build self.package_builds_by_name={'snapd': <pikaur.build.PackageBuild object at 0x7f428c673280>}
:: debug: Gonna build pkg_build.package_names=['snapd']
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp mkdir -p /var/cache/private/pikaur/build/snapd
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp cp -r /var/cache/private/pikaur/aur_repos/snapd/last_installed.txt /var/cache/private/pikaur/aur_repos/snapd/PKGBUILD /var/cache/private/pikaur/aur_repos/snapd/snapd.install /var/cache/private/pikaur/aur_repos/snapd/.gitignore /var/cache/private/pikaur/aur_repos/snapd/.SRCINFO /var/cache/private/pikaur/build/snapd/
=> pacman --color=always --deptest squashfs-tools libseccomp libsystemd apparmor
=> pacman --color=always --deptest git go go-tools libseccomp libcap systemd xfsprogs python-docutils apparmor
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/snapd makepkg --packagelist

:: Sto iniziando la creazione del pacchetto:
=> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/snapd makepkg --force
```
**Stuck at this**

**Comment by actionless** [comment] 2020-04-12 18:33
> systemd-run --service-type=oneshot --pipe --wait --pty -p DynamicUser=yes -p CacheDirectory=pikaur -E HOME=/tmp -p WorkingDirectory=/var/cache/pikaur/build/snapd makepkg --force

a duplicate of https://github.com/actionless/pikaur/issues/469

**Closed by actionless** 2020-04-12 18:33 UTC
