### ISSUE TITLE
After the latest update in Manjaro-rpi4, Pikaur stopped working

### ISSUE THREAD

**Issue by kerabromsmu** [actionless/pikaur#802] opened 2024-05-31 15:43 UTC
```
pikaur -Vq

```

##### [Optional] Prerequisites:
Running in Manjaro on Raspberry Pi 4 (6.9.1-1-MANJARO-RPI4)
update the pikaur to the latest version (pikaur-1.21-1 or pikaur-git 1.21.r9.g4862e8a-1)

##### Description:
When I run pikaur with or without any parameters after the update, it shows a syntax error instead of doing anything

##### Attached log:

```
pikaur
Traceback (most recent call last):
  File "/usr/bin/pikaur", line 6, in <module>
    from pikaur.main import main
  File "/usr/lib/python3.11/site-packages/pikaur/main.py", line 40, in <module>
    from .install_cli import InstallPackagesCLI
  File "/usr/lib/python3.11/site-packages/pikaur/install_cli.py", line 292
    ),
    ^
SyntaxError: f-string expression part cannot include a backslash
```

**Comment by amiga23** [comment] 2024-05-31 16:10
Duplicate of #800

**Closed** 2024-05-31 18:47 UTC
