### ISSUE TITLE
Show arch news on sysupgrade

### ISSUE THREAD

**Issue by actionless** [actionless/pikaur#59] opened 2018-03-05 06:49 UTC
https://www.archlinux.org/news/

most of the time that information is crucial during sysupgrade

**Comment by Tyilo** [comment] 2018-03-05 08:37
I have thought about creating this issue myself, as I think it is a good idea.

**Comment by actionless** [comment] 2018-03-25 15:46
i think i need more opinions on designing this feature, there are some interesting aspects of implementing it:

1) should the last upgrade date have to be taken into account (ie showing arch news only released after the last upgrade datetime)
2) one of alternative approaches could be showing arch news for last month and ask user to confirm what they were read and just save on the disk a file with last read date
3) something else?

**Comment by KopfKrieg** [comment] 2018-03-25 16:25
I'd take option number 1, only show news released after the last upgrade. I wouldn't ask the user to confirm anything, I'd just show it in the output, e.g.:

```
$ sudo pikaur -Syu
[…]
:: Starting full system upgrade...
:: Starting full AUR upgrade...
Reading local package database...
Reading repository package databases...
Reading AUR packages info...

:: Repository package will be installed:
 python-dateutil                      2.7.0-1            -> 2.7.1-1

:: News
2018-02-22 zita-resampler 1.6.0-1 -> 2 update requires manual intervention
 - https://www.archlinux.org/news/zita-resampler-160-1-2-update-requires-manual-intervention/

:: Proceed with installation? [Y/n]
:: [v]iew package detail   [m]anually select packages
```

So, just the date, the title and a link (because, if you're using a terminal in a desktop environment, you should be able to click it and open the site without any copy/pasting and/or searching).

Maybe add an option `[v]iew package detail [m]anually select packages [r]ead news` or something like that if you want to provide a way to read the whole message within the terminal.

**Comment by masterodie** [comment] 2018-05-14 19:19
Maybe just wrap your call to pacman with [pacmatic](https://github.com/keenerd/pacmatic) for this if it is installed.

**Comment by actionless** [comment] 2018-05-14 19:26
but i need only one quite small part from there:
https://github.com/keenerd/pacmatic/blob/master/pacmatic#L114-L145

**Comment by actionless** [comment] 2018-05-14 19:28
i can also guide from where approximately in pikaur such function should be called, but, sorry, i don't have time working on it right now

**Comment by masterodie** [comment] 2018-05-14 19:47
shouldn't be too hard too implement. just call pacmatic instead of pacman if pacmatic is found in $PATH. 

or to use it as intended just call pikaur through pacmatic with `export pacman_progam=pikaur` in your bashrc for example. and than run pamatic for instead of pikaur.

Displays news before upgrade and does a check for .pacnew files after installation.

http://kmkeen.com/pacmatic/ for more info.

**Comment by actionless** [comment] 2018-05-14 19:58
what can i do here -- do make pikaur care of `PIKAUR_PACMAN_PATH` env var to set executable of pacman, what do you think?

**Comment by actionless** [comment] 2018-05-14 19:59
or it can be done as config option, to be more uniform with already existing functionality

**Comment by actionless** [comment] 2018-05-14 20:02
but still later on it will be nice to implement arch news support in pikaur itself, since it's not quite a lot of code to write (one of project goals is to avoid depending on AUR packages to simplify bootstrapping)

**Comment by masterodie** [comment] 2018-05-14 20:16
I would say make it a config option. And if you want to implement it later on a check for .pacnew files would be nice too.

**Comment by Bundy01** [comment] 2018-05-19 15:46
The news option is a very good idea. I hope she will be in pikaur very soon. Good continuation :)

**Comment by steven-omaha** [comment] 2018-05-30 15:55
I think I'm gonna start working on this one. I'll try to keep the dependencies minimal, which means getting the RSS feed by a socket, some very basic RSS parsing by string manipulation, and caching the last shown news in `$XDG_CACHE_HOME/pikaur/last_seen_news.dat`.

**Comment by actionless** [comment] 2018-05-30 16:04
why not to use `lxml` for rss parsing?

**Comment by steven-omaha** [comment] 2018-05-30 17:30
Didn't know that `xml` was part of core python. That makes it easier.

**Comment by steven-omaha** [comment] 2018-05-30 20:10
I made [a first commit](https://github.com/steven-omaha/pikaur/commit/647a5246d51552e3e1157d4c38f3605f0400133c) for the functionality requested here. This isn't final by any means, but rather a suggestion and still quite messy. The integration with your configuration (line max_width for text wrapping, internatiolization) comes later. My code uses only python standard libraries. Feel free to to criticise.

If you run `python pikaur/news.py`, it will create `~/.cache/pikaur/last_seen_news.dat`. When you change the year e.g. to 2017, and re-execute, you should be able to see some news entries.

**Comment by actionless** [comment] 2018-05-30 20:15
looks good from the first glance, you were rapid on this!

suggestions to improve:
1) use type hints for variables
2) use coloring/bold font from pikaur.pprint

**Comment by actionless** [comment] 2018-05-30 20:16
3) get initial date (if dat-file not present) from last installed local package from the repo

**Comment by actionless** [comment] 2018-05-30 20:18
4. take `max_width` from `pikaur.pprint.get_term_width()`

**Comment by steven-omaha** [comment] 2018-05-30 20:27
[Like so?](https://github.com/actionless/pikaur/pull/191)

**Comment by actionless** [comment] 2018-05-30 20:31
yup, thanks!

**Comment by Bundy01** [comment] 2018-06-01 18:05
Hi,
@actionless: I see it's coming. Otherwise I found a script that might match. To modify very slightly: [https://github.com/mjiricka/archnews/blob/master/archnews_wrap](url)  

What would be nice is to modify the address'FEED_URL' in the pikaur.conf file, for different languages.

To run this script, I changed 'PACKAGE_MANAGER_FULL_PATH_DEFAULT' to **/usr/bin/pikaur**, the address'FEED_URL' and created an alias in .bashrc or .zshrc ... 
**alias pikaur='archnews_wrap'** (alias to be modified according to the rewritten script name). Hoping to help with this option and that this script will inspire you :)

**Comment by steven-omaha** [comment] 2018-06-01 22:30
@Bundy01 Thanks for your input. Unfortunately, I was kind of finished when you brought up your idea. 

I don't really like the idea of having a separate tool that wraps around pikaur, because

1. this violates pikaur's goal of "minimal dependencies",
2. the wrapper does not integrate so nicely into pikaur itself,
3. the archnews tool does a lot more than only showing news if there are some, actually parses its own arguments. The program looks like it is quite interactive, which conflicts with the original pacaur idea that pikaur aims to copy (and does so actually quite nicely!). Finally, 
4. archnews has 600 LOC compared to 160 in [my solution](https://github.com/steven-omaha/pikaur/blob/news/pikaur/news.py).

**Closed** 2018-06-03 08:57 UTC
Labels: feature, in progress
