### ISSUE TITLE
Ask for confirmation after download/install/upgrade size has been shown

### ISSUE THREAD

**Issue by felixwiemuth** [actionless/pikaur#393] opened 2019-09-14 12:19 UTC
```
Pikaur v1.4.4
Pacman v5.1.3 - libalpm v11.0.3
```
I found it quite useful that pacman shows the download, install and net upgrade size before an upgrade/installation before asking for confirmation. This does currently not seem possible with pikaur (e.g. `pikaur -Syu --confirm` would still not stop there).

Regarding #122, is it completely impossible to stop where pacman usually ask for confirmation?

Optimal would of course be, if pikaur could show this information before it asks for the "main" confirmation and then pacman runs through as it does now.

I see the following options to enable this (but I don't know how pikaur is implemented, so not all might make sense):
1. Let pacman run until the point where it would ask for confirmation, but without showing the output, just extracting the download/install/upgrade sizes and show them to the user before asking for confirmation. Then, after confirmation, run as now.
2. Do the calculations in pikaur.
3. Optionally, let pacman ask for confirmation as well.

**Comment by actionless** [comment] 2019-09-15 00:21
duplicate of https://github.com/actionless/pikaur/issues/311

**Closed by actionless** 2019-09-15 00:21 UTC
