### ISSUE TITLE
How to disable warning

### ISSUE THREAD

**Issue by groodle** [actionless/pikaur#814] opened 2024-06-23 05:33 UTC
I would really like to disable the following warning:

```
:: warning:
Read damn arch-wiki before borking your computer
https://wiki.archlinux.org/title/Arch_User_Repository
```

That appears twice when I use pikaur. I've checked the man page, the README here and my pikaur.conf file and I can't see any option in there to disable this warning.

Is there any way to disable this warning?

BTW, thanks for the great package!

**Comment by amiga23** [comment] 2024-06-23 08:37
It's never good to disable a warning, but better to solve the root cause. Please check already closed issues, your's is a duplicate of an already reported one.

**Comment by actionless** [comment] 2024-06-23 15:16
>  I've checked the man page, the README here and my pikaur.conf file and I can't see any option in there to disable this warning.

that's weird that you checked everything BUT the link in the warnings message 😿

**Closed by actionless** 2024-06-23 15:16 UTC

**Comment by M1CK431** [comment] 2024-08-14 14:29
@groodle this warning is raised because `base-devel` is not installed.
Thanks to @xPMo who nicely explain that here: https://github.com/actionless/pikaur/issues/812#issuecomment-2180890101

I'm posting the solution here too in the hope that it could help other people which (like me):
- are using Archlinux for years (something like a decade)
- don't modify there working setup after the switch of `base-devel` from package group to meta package
- can compile any AUR package without any issue
- read the "damn arch-wiki" page without remember about the `base-devel` state change (and so no any chance to think about installing it)

Like many others before me, I sadly deplore the lack of pedagogy of this message and truly don't understand why @actionless refuse to update it to something more meaningful like, for example:
> `base-devel` package seems not installed on your system, building package from AUR may fail. If you don't know how to install it, visit https://wiki.archlinux.org/title/Arch_User_Repository

With such message, it's unlikely to see new issues like this one in the futur, allowing @actionless to stay focus on enhancing such great tool like Pikaur 😘
