### ISSUE TITLE
Can't install AUR package that requires specific version of dependencies

### ISSUE THREAD

**Issue by pklapperich** [actionless/pikaur#409] opened 2019-10-17 07:55 UTC
```
$ pikaur -Vq
Pikaur v1.4.3.r25.g9a16936
Pacman v5.1.3 - libalpm v11.0.3


```

##### [Optional] Prerequisites:
I don't think there are any

##### Attached log:

```
$ pikaur -S gazebo
Reading repository package databases...
Reading local package database...
Resolving AUR dependencies...
:: error: Can't resolve dependencies for AUR package 'gazebo':
Version mismatch:
gazebo depends on: 'ignition-math=4'
 found in 'PackageSource.AUR': '6.2.0-4'
$ pikaur -Ss ignition-math
Searching... [###]
aur/ignition-math 6.2.0-4 (9, 0.08)
    Math classes and functions for robot applications    
aur/ignition-math-hg 2.1.1.434-1 (1, 0.00)
    Math classes and functions for robot applications    
aur/ignition-math-4 4.0.0-2 (0, 0.00)
    Math classes and functions for robot applications

```

I was able to successfully install this package using another AUR helper, so it does build, at least today.

**Comment by actionless** [comment] 2019-10-18 08:06
duplicate of https://github.com/actionless/pikaur/issues/402

**Closed by actionless** 2019-10-18 08:06 UTC

**Comment by actionless** [comment] 2024-06-14 18:52
Thanks for reporting!
You can check with `pikaur-git` AUR package if it works for you now.
